import type { Metadata } from "next";
import { DM_Serif_Text, Inter, Roboto } from "next/font/google";
import "./globals.css";
import Providers from "@/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <Providers>{children}</Providers>
    </html>
  );
}
